<?php

return [
    'id' => 'show_id',
    'name' => 'Show Name',
    'start_date' => 'Date From',
    'end_date' => 'Date To',
    'year' => 'Year',
    'location' => 'Location',
    'country' => 'Country',
    'prize_money' => 'Show Prize Money',
    'events_count' => 'Number Of Events',
    'horse_per_show' => 'Horse Per Show',
    'logo' => 'LOGO',
    'fei_prog' => 'FEI_Prog',
    'currency' => 'Currency',
    'k_sponsor_1' => 'ksponsor1logo',
    'k_sponsor_2' => 'ksponsor2logo',
    'k_sponsor_3' => 'ksponsor3logo',
    'k_sponsor_4' => 'ksponsor4logo',
    'k_sponsor_5' => 'ksponsor5logo',
    'k_sponsor_6' => 'ksponsor6logo',
    'filemaker_timestamp' => 'modification timestamp',
    'organizer_name' => 'Organizer Name',
    'organizer_contact' => 'Organizer Contact',
    'organizer_address' => 'Organizer Address',
];